# Generated by Django 6.0.3 on 2026-03-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=10),
            preserve_default=False,
        ),
    ]
